# **Phase 1: Faster R-CNN Training on DAWN (In-domain DAWN -> DAWN)**

This notebook trains and evaluates a Faster R-CNN baseline on the DAWN dataset under an in-domain setting.

Notes:
- This preliminary implementation uses TorchVision's official Faster R-CNN implementation.
- Detectron2 is planned for the final extended experiments.

Experiment summary:
- Model: Faster R-CNN (TorchVision implementation)
- Protocol: In-domain (DAWN → DAWN)
- Dataset: DAWN
- Format: Pascal VOC
- Subset setting: reduced train/val/weather subsets
- Purpose: preliminary two-stage baseline for comparison with YOLOv11

### Connect to Google Drive

In [1]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

### **Paths**

In [2]:
from pathlib import Path

RANDOM_SEED = 456

PROJECT_ROOT = Path("/content/drive/MyDrive/Dissertation")

DAWN_VOC_ROOT = PROJECT_ROOT / "Datasets" / "processed" / "dawn_voc"
RUNS_ROOT = PROJECT_ROOT / "Runs" / "faster_rcnn"
EXPERIMENT_NAME = "dawn_indomain_fasterrcnn_r50fpn_seed456"
OUTPUT_DIR = RUNS_ROOT / EXPERIMENT_NAME
OUTPUT_DIR.mkdir(parents=True, exist_ok=True)

print("PROJECT_ROOT:", PROJECT_ROOT, PROJECT_ROOT.exists())
print("DAWN_VOC_ROOT:", DAWN_VOC_ROOT, DAWN_VOC_ROOT.exists())
print("OUTPUT_DIR:", OUTPUT_DIR)

print("JPEGImages:", (DAWN_VOC_ROOT / "JPEGImages").exists())
print("Annotations:", (DAWN_VOC_ROOT / "Annotations").exists())
print("ImageSets/Main:", (DAWN_VOC_ROOT / "ImageSets" / "Main").exists())

for split in ["train", "val", "test_fog", "test_rain", "test_snow"]:
    split_file = DAWN_VOC_ROOT / "ImageSets" / "Main" / f"{split}.txt"
    print(split, split_file.exists(), split_file)

PROJECT_ROOT: /content/drive/MyDrive/Dissertation True
DAWN_VOC_ROOT: /content/drive/MyDrive/Dissertation/Datasets/processed/dawn_voc True
OUTPUT_DIR: /content/drive/MyDrive/Dissertation/Runs/faster_rcnn/dawn_indomain_fasterrcnn_r50fpn_seed456
JPEGImages: True
Annotations: True
ImageSets/Main: True
train True /content/drive/MyDrive/Dissertation/Datasets/processed/dawn_voc/ImageSets/Main/train.txt
val True /content/drive/MyDrive/Dissertation/Datasets/processed/dawn_voc/ImageSets/Main/val.txt
test_fog True /content/drive/MyDrive/Dissertation/Datasets/processed/dawn_voc/ImageSets/Main/test_fog.txt
test_rain True /content/drive/MyDrive/Dissertation/Datasets/processed/dawn_voc/ImageSets/Main/test_rain.txt
test_snow True /content/drive/MyDrive/Dissertation/Datasets/processed/dawn_voc/ImageSets/Main/test_snow.txt

# **Install Detectron**

In [3]:
# Fix numpy compatibility
!pip install -q --force-reinstall numpy==1.26.4

# Build dependencies
!pip install -q setuptools==68.0.0 wheel cython

#Import detectron from the source
%cd /content

import os

if not os.path.exists("/content/detectron2"):
    !git clone https://github.com/facebookresearch/detectron2.git

%cd /content/detectron2
!python -m pip install --no-build-isolation -e .
%cd /content

ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
tobler 0.14.0 requires numpy>=2.0, but you have numpy 1.26.4 which is incompatible.
opencv-python 4.13.0.92 requires numpy>=2; python_version >= "3.9", but you have numpy 1.26.4 which is incompatible.
xarray-einstats 0.10.0 requires numpy>=2.0, but you have numpy 1.26.4 which is incompatible.
opencv-contrib-python 4.13.0.92 requires numpy>=2; python_version >= "3.9", but you have numpy 1.26.4 which is incompatible.
jaxlib 0.7.2 requires numpy>=2.0, but you have numpy 1.26.4 which is incompatible.
pytensor 2.38.3 requires numpy>=2.0, but you have numpy 1.26.4 which is incompatible.
shap 0.52.0 requires numpy>=2, but you have numpy 1.26.4 which is incompatible.
opencv-python-headless 4.13.0.92 requires numpy>=2; python_version >= "3.9", but you have numpy 1.26.4 which is incompatible.
tifffile 2026.4.11 requires numpy>=2.0, but you have numpy 1.26.4 which is incompatible.
rasterio 1.5.0 requires numpy>=2, but you have numpy 1.26.4 which is incompatible.
jax 0.7.2 requires numpy>=2.0, but you have numpy 1.26.4 which is incompatible.
cupy-cuda12x 14.0.1 requires numpy<2.6,>=2.0, but you have numpy 1.26.4 which is incompatible.
/content
/content/detectron2
Obtaining file:///content/detectron2
  Preparing metadata (setup.py) ... done
Requirement already satisfied: Pillow>=7.1 in /usr/local/lib/python3.12/dist-packages (from detectron2==0.6) (11.3.0)
Requirement already satisfied: matplotlib in /usr/local/lib/python3.12/dist-packages (from detectron2==0.6) (3.10.0)
Requirement already satisfied: pycocotools>=2.0.2 in /usr/local/lib/python3.12/dist-packages (from detectron2==0.6) (2.0.11)
Requirement already satisfied: termcolor>=1.1 in /usr/local/lib/python3.12/dist-packages (from detectron2==0.6) (3.3.0)
Requirement already satisfied: yacs>=0.1.8 in /usr/local/lib/python3.12/dist-packages (from detectron2==0.6) (0.1.8)
Requirement already satisfied: tabulate in /usr/local/lib/python3.12/dist-packages (from detectron2==0.6) (0.9.0)
Requirement already satisfied: cloudpickle in /usr/local/lib/python3.12/dist-packages (from detectron2==0.6) (3.1.2)
Requirement already satisfied: tqdm>4.29.0 in /usr/local/lib/python3.12/dist-packages (from detectron2==0.6) (4.67.3)
Requirement already satisfied: tensorboard in /usr/local/lib/python3.12/dist-packages (from detectron2==0.6) (2.20.0)
Requirement already satisfied: fvcore<0.1.6,>=0.1.5 in /usr/local/lib/python3.12/dist-packages (from detectron2==0.6) (0.1.5.post20221221)
Requirement already satisfied: iopath<0.1.10,>=0.1.7 in /usr/local/lib/python3.12/dist-packages (from detectron2==0.6) (0.1.9)
Requirement already satisfied: omegaconf<2.4,>=2.1 in /usr/local/lib/python3.12/dist-packages (from detectron2==0.6) (2.3.1)
Requirement already satisfied: hydra-core>=1.1 in /usr/local/lib/python3.12/dist-packages (from detectron2==0.6) (1.3.4)
Requirement already satisfied: black in /usr/local/lib/python3.12/dist-packages (from detectron2==0.6) (26.5.1)
Requirement already satisfied: packaging in /usr/local/lib/python3.12/dist-packages (from detectron2==0.6) (26.2)
Requirement already satisfied: numpy in /usr/local/lib/python3.12/dist-packages (from fvcore<0.1.6,>=0.1.5->detectron2==0.6) (1.26.4)
Requirement already satisfied: pyyaml>=5.1 in /usr/local/lib/python3.12/dist-packages (from fvcore<0.1.6,>=0.1.5->detectron2==0.6) (6.0.3)
Requirement already satisfied: antlr4-python3-runtime==4.9.* in /usr/local/lib/python3.12/dist-packages (from hydra-core>=1.1->detectron2==0.6) (4.9.3)
Requirement already satisfied: portalocker in /usr/local/lib/python3.12/dist-packages (from iopath<0.1.10,>=0.1.7->detectron2==0.6) (3.2.0)
Requirement already satisfied: click>=8.0.0 in /usr/local/lib/python3.12/dist-packages (from black->detectron2==0.6) (8.4.2)
Requirement already satisfied: mypy-extensions>=0.4.3 in /usr/local/lib/python3.12/dist-packages (from black->detectron2==0.6) (1.1.0)
Requirement already satisfied: pathspec>=1.0.0 in /usr/local/lib/python3.12/dist-packages (from black->detectron2==0.6) (1.1.1)
Requirement already satisfied: platformdirs>=2 in /usr/local/lib/python3.12/dist-packages (from black->detectron2==0.6) (4.10.0)
Requirement already satisfied: pytokens~=0.4.0 in /usr/local/lib/python3.12/dist-packages (from black->detectron2==0.6) (0.4.1)
Requirement already satisfied: contourpy>=1.0.1 in /usr/local/lib/python3.12/dist-packages (from matplotlib->detectron2==0.6) (1.3.3)
Requirement already satisfied: cycler>=0.10 in /usr/local/lib/python3.12/dist-packages (from matplotlib->detectron2==0.6) (0.12.1)
Requirement already satisfied: fonttools>=4.22.0 in /usr/local/lib/python3.12/dist-packages (from matplotlib->detectron2==0.6) (4.63.0)
Requirement already satisfied: kiwisolver>=1.3.1 in /usr/local/lib/python3.12/dist-packages (from matplotlib->detectron2==0.6) (1.5.0)
Requirement already satisfied: pyparsing>=2.3.1 in /usr/local/lib/python3.12/dist-packages (from matplotlib->detectron2==0.6) (3.3.2)
Requirement already satisfied: python-dateutil>=2.7 in /usr/local/lib/python3.12/dist-packages (from matplotlib->detectron2==0.6) (2.9.0.post0)
Requirement already satisfied: absl-py>=0.4 in /usr/local/lib/python3.12/dist-packages (from tensorboard->detectron2==0.6) (1.4.0)
Requirement already satisfied: grpcio>=1.48.2 in /usr/local/lib/python3.12/dist-packages (from tensorboard->detectron2==0.6) (1.81.1)
Requirement already satisfied: markdown>=2.6.8 in /usr/local/lib/python3.12/dist-packages (from tensorboard->detectron2==0.6) (3.10.2)
Requirement already satisfied: protobuf!=4.24.0,>=3.19.6 in /usr/local/lib/python3.12/dist-packages (from tensorboard->detectron2==0.6) (5.29.6)
Requirement already satisfied: setuptools>=41.0.0 in /usr/local/lib/python3.12/dist-packages (from tensorboard->detectron2==0.6) (68.0.0)
Requirement already satisfied: tensorboard-data-server<0.8.0,>=0.7.0 in /usr/local/lib/python3.12/dist-packages (from tensorboard->detectron2==0.6) (0.7.2)
Requirement already satisfied: werkzeug>=1.0.1 in /usr/local/lib/python3.12/dist-packages (from tensorboard->detectron2==0.6) (3.1.8)
Requirement already satisfied: typing-extensions~=4.12 in /usr/local/lib/python3.12/dist-packages (from grpcio>=1.48.2->tensorboard->detectron2==0.6) (4.15.0)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from python-dateutil>=2.7->matplotlib->detectron2==0.6) (1.17.0)
Requirement already satisfied: markupsafe>=2.1.1 in /usr/local/lib/python3.12/dist-packages (from werkzeug>=1.0.1->tensorboard->detectron2==0.6) (3.0.3)
Installing collected packages: detectron2
  Attempting uninstall: detectron2
    Found existing installation: detectron2 0.6
    Uninstalling detectron2-0.6:
      Successfully uninstalled detectron2-0.6
  Running setup.py develop for detectron2
Successfully installed detectron2-0.6
/content

In [ ]:
import os
os.kill(os.getpid(), 9)

In [4]:
import numpy as np
print(np.__version__)

1.26.4

# **Imports libraires**

In [5]:
import detectron2
print("Detectron2 imported successfully.")

Detectron2 imported successfully.

### Force detectron path

In [6]:
import sys

# Remove all cached detectron2 modules
for module_name in list(sys.modules.keys()):
    if module_name.startswith("detectron2"):
        del sys.modules[module_name]

# Force GitHub Detectron2 path
sys.path = [p for p in sys.path if "detectron2" not in p.lower()]
sys.path.insert(0, "/content/detectron2")

import detectron2
print(detectron2.__file__)

/content/detectron2/detectron2/__init__.py

In [7]:
!pip install -q torchmetrics

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 983.4/983.4 kB 63.3 MB/s eta 0:00:00

In [8]:
import os
import json
import random
import math
from pathlib import Path
import torch
import time

import numpy as np
import pandas as pd
import torch
import cv2

from detectron2 import model_zoo
from detectron2.config import get_cfg
from detectron2.engine import DefaultTrainer, DefaultPredictor, hooks
from detectron2.data import DatasetCatalog, MetadataCatalog
from detectron2.data.datasets import register_pascal_voc
from detectron2.utils.logger import setup_logger
from detectron2.data.datasets import register_pascal_voc
from detectron2.data import DatasetCatalog, MetadataCatalog
from detectron2.structures import BoxMode
from detectron2.checkpoint import DetectionCheckpointer
from detectron2.evaluation import COCOEvaluator, inference_on_dataset
from detectron2.data import build_detection_test_loader

setup_logger()

# **Registration + Verification**

In [13]:
CLASS_NAMES = ["person", "bicycle", "car", "motorcycle", "bus", "truck"]

datasets = {
    "dawn_train": "train",
    "dawn_val": "val",
    "dawn_test_fog": "test_fog",
    "dawn_test_rain": "test_rain",
    "dawn_test_snow": "test_snow",
}

def reset_detectron2_dataset(name):
    if name in DatasetCatalog.list():
        DatasetCatalog.remove(name)
    if name in MetadataCatalog.list():
        MetadataCatalog.remove(name)

for dataset_name in datasets:
    reset_detectron2_dataset(dataset_name)

for dataset_name, split_name in datasets.items():
    register_pascal_voc(
        name=dataset_name,
        dirname=str(DAWN_VOC_ROOT),
        split=split_name,
        year="",
        class_names=CLASS_NAMES
    )

print("DAWN datasets registered.")

DAWN datasets registered.

In [14]:
for dataset_name in datasets:
    d = DatasetCatalog.get(dataset_name)
    print(dataset_name, ":", len(d), "images")
    print(MetadataCatalog.get(dataset_name).thing_classes)

dawn_train : 423 images
['person', 'bicycle', 'car', 'motorcycle', 'bus', 'truck']
dawn_val : 140 images
['person', 'bicycle', 'car', 'motorcycle', 'bus', 'truck']
dawn_test_fog : 60 images
['person', 'bicycle', 'car', 'motorcycle', 'bus', 'truck']
dawn_test_rain : 40 images
['person', 'bicycle', 'car', 'motorcycle', 'bus', 'truck']
dawn_test_snow : 40 images
['person', 'bicycle', 'car', 'motorcycle', 'bus', 'truck']

# **Training Configuration**

In [15]:
seed = RANDOM_SEED

random.seed(seed)
np.random.seed(seed)
torch.manual_seed(seed)
torch.cuda.manual_seed_all(seed)

IMS_PER_BATCH = 4
EPOCHS = 100

train_size = len(DatasetCatalog.get("dawn_train"))
iters_per_epoch = math.ceil(train_size / IMS_PER_BATCH)
MAX_ITER = EPOCHS * iters_per_epoch

CHECKPOINT_PERIOD = iters_per_epoch * 10
EVAL_PERIOD = iters_per_epoch

print("Train size:", train_size)
print("Iterations per epoch:", iters_per_epoch)
print("Max iterations:", MAX_ITER)
print("Checkpoint period:", CHECKPOINT_PERIOD)
print("Eval period:", EVAL_PERIOD)

Train size: 423
Iterations per epoch: 106
Max iterations: 10600
Checkpoint period: 1060
Eval period: 106

# **Trainer with BestCheckPointer**

In [17]:
class TrainerWithBestCheckpoint(DefaultTrainer):
    @classmethod
    def build_evaluator(cls, cfg, dataset_name, output_folder=None):
        if output_folder is None:
            output_folder = os.path.join(cfg.OUTPUT_DIR, "eval", dataset_name)
        return COCOEvaluator(dataset_name, cfg, False, output_folder)

    def build_hooks(self):
        hook_list = super().build_hooks()

        hook_list.insert(
            -1,
            hooks.BestCheckpointer(
                self.cfg.TEST.EVAL_PERIOD,
                DetectionCheckpointer(self.model, self.cfg.OUTPUT_DIR),
                "bbox/AP",
                mode="max",
                file_prefix="model_best"
            )
        )

        return hook_list

### **Build cfg**

In [16]:
cfg = get_cfg()

cfg.merge_from_file(
    model_zoo.get_config_file("COCO-Detection/faster_rcnn_R_50_FPN_3x.yaml")
)

cfg.MODEL.WEIGHTS = model_zoo.get_checkpoint_url(
    "COCO-Detection/faster_rcnn_R_50_FPN_3x.yaml"
)

cfg.DATASETS.TRAIN = ("dawn_train",)
cfg.DATASETS.TEST = ("dawn_val",)

cfg.DATALOADER.NUM_WORKERS = 2

cfg.MODEL.ROI_HEADS.NUM_CLASSES = len(CLASS_NAMES)
cfg.MODEL.ROI_HEADS.SCORE_THRESH_TEST = 0.5

cfg.SOLVER.IMS_PER_BATCH = IMS_PER_BATCH
cfg.SOLVER.BASE_LR = 0.001
cfg.SOLVER.MOMENTUM = 0.9
cfg.SOLVER.WEIGHT_DECAY = 0.0001

cfg.SOLVER.MAX_ITER = MAX_ITER
cfg.SOLVER.STEPS = []
cfg.SOLVER.CHECKPOINT_PERIOD = CHECKPOINT_PERIOD

cfg.TEST.EVAL_PERIOD = EVAL_PERIOD

cfg.OUTPUT_DIR = str(OUTPUT_DIR)
cfg.SEED = seed

os.makedirs(cfg.OUTPUT_DIR, exist_ok=True)

with open(OUTPUT_DIR / "config.yaml", "w") as f:
    f.write(cfg.dump())

print("Config ready.")
print("MAX_ITER:", cfg.SOLVER.MAX_ITER)
print("OUTPUT_DIR:", cfg.OUTPUT_DIR)

Config ready.
MAX_ITER: 10600
OUTPUT_DIR: /content/drive/MyDrive/Dissertation/Runs/faster_rcnn/dawn_indomain_fasterrcnn_r50fpn_seed456

### **Train**

In [ ]:
trainer = TrainerWithBestCheckpoint(cfg)
trainer.resume_or_load(resume=False)
trainer.train()

[07/16 06:29:16 d2.engine.defaults]: Model:
GeneralizedRCNN(
  (backbone): FPN(
    (fpn_lateral2): Conv2d(256, 256, kernel_size=(1, 1), stride=(1, 1))
    (fpn_output2): Conv2d(256, 256, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
    (fpn_lateral3): Conv2d(512, 256, kernel_size=(1, 1), stride=(1, 1))
    (fpn_output3): Conv2d(256, 256, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
    (fpn_lateral4): Conv2d(1024, 256, kernel_size=(1, 1), stride=(1, 1))
    (fpn_output4): Conv2d(256, 256, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
    (fpn_lateral5): Conv2d(2048, 256, kernel_size=(1, 1), stride=(1, 1))
    (fpn_output5): Conv2d(256, 256, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
    (top_block): LastLevelMaxPool()
    (bottom_up): ResNet(
      (stem): BasicStem(
        (conv1): Conv2d(
          3, 64, kernel_size=(7, 7), stride=(2, 2), padding=(3, 3), bias=False
          (norm): FrozenBatchNorm2d(num_features=64, eps=1e-05)
        )
      )
      (res2): Sequential(
        (0): BottleneckBlock(
          (shortcut): Conv2d(
            64, 256, kernel_size=(1, 1), stride=(1, 1), bias=False
            (norm): FrozenBatchNorm2d(num_features=256, eps=1e-05)
          )
          (conv1): Conv2d(
            64, 64, kernel_size=(1, 1), stride=(1, 1), bias=False
            (norm): FrozenBatchNorm2d(num_features=64, eps=1e-05)
          )
          (conv2): Conv2d(
            64, 64, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1), bias=False
            (norm): FrozenBatchNorm2d(num_features=64, eps=1e-05)
          )
          (conv3): Conv2d(
            64, 256, kernel_size=(1, 1), stride=(1, 1), bias=False
            (norm): FrozenBatchNorm2d(num_features=256, eps=1e-05)
          )
        )
        (1): BottleneckBlock(
          (conv1): Conv2d(
            256, 64, kernel_size=(1, 1), stride=(1, 1), bias=False
            (norm): FrozenBatchNorm2d(num_features=64, eps=1e-05)
          )
          (conv2): Conv2d(
            64, 64, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1), bias=False
            (norm): FrozenBatchNorm2d(num_features=64, eps=1e-05)
          )
          (conv3): Conv2d(
            64, 256, kernel_size=(1, 1), stride=(1, 1), bias=False
            (norm): FrozenBatchNorm2d(num_features=256, eps=1e-05)
          )
        )
        (2): BottleneckBlock(
          (conv1): Conv2d(
            256, 64, kernel_size=(1, 1), stride=(1, 1), bias=False
            (norm): FrozenBatchNorm2d(num_features=64, eps=1e-05)
          )
          (conv2): Conv2d(
            64, 64, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1), bias=False
            (norm): FrozenBatchNorm2d(num_features=64, eps=1e-05)
          )
          (conv3): Conv2d(
            64, 256, kernel_size=(1, 1), stride=(1, 1), bias=False
            (norm): FrozenBatchNorm2d(num_features=256, eps=1e-05)
          )
        )
      )
      (res3): Sequential(
        (0): BottleneckBlock(
          (shortcut): Conv2d(
            256, 512, kernel_size=(1, 1), stride=(2, 2), bias=False
            (norm): FrozenBatchNorm2d(num_features=512, eps=1e-05)
          )
          (conv1): Conv2d(
            256, 128, kernel_size=(1, 1), stride=(2, 2), bias=False
            (norm): FrozenBatchNorm2d(num_features=128, eps=1e-05)
          )
          (conv2): Conv2d(
            128, 128, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1), bias=False
            (norm): FrozenBatchNorm2d(num_features=128, eps=1e-05)
          )
          (conv3): Conv2d(
            128, 512, kernel_size=(1, 1), stride=(1, 1), bias=False
            (norm): FrozenBatchNorm2d(num_features=512, eps=1e-05)
          )
        )
        (1): BottleneckBlock(
          (conv1): Conv2d(
            512, 128, kernel_size=(1, 1), stride=(1, 1), bias=False
            (norm): FrozenBatchNorm2d(num_features=128, eps=1e-05)
          )
          (conv2): Conv2d(
            128, 128, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1), bias=False
            (norm): FrozenBatchNorm2d(num_features=128, eps=1e-05)
          )
          (conv3): Conv2d(
            128, 512, kernel_size=(1, 1), stride=(1, 1), bias=False
            (norm): FrozenBatchNorm2d(num_features=512, eps=1e-05)
          )
        )
        (2): BottleneckBlock(
          (conv1): Conv2d(
            512, 128, kernel_size=(1, 1), stride=(1, 1), bias=False
            (norm): FrozenBatchNorm2d(num_features=128, eps=1e-05)
          )
          (conv2): Conv2d(
            128, 128, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1), bias=False
            (norm): FrozenBatchNorm2d(num_features=128, eps=1e-05)
          )
          (conv3): Conv2d(
            128, 512, kernel_size=(1, 1), stride=(1, 1), bias=False
            (norm): FrozenBatchNorm2d(num_features=512, eps=1e-05)
          )
        )
        (3): BottleneckBlock(
          (conv1): Conv2d(
            512, 128, kernel_size=(1, 1), stride=(1, 1), bias=False
            (norm): FrozenBatchNorm2d(num_features=128, eps=1e-05)
          )
          (conv2): Conv2d(
            128, 128, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1), bias=False
            (norm): FrozenBatchNorm2d(num_features=128, eps=1e-05)
          )
          (conv3): Conv2d(
            128, 512, kernel_size=(1, 1), stride=(1, 1), bias=False
            (norm): FrozenBatchNorm2d(num_features=512, eps=1e-05)
          )
        )
      )
      (res4): Sequential(
        (0): BottleneckBlock(
          (shortcut): Conv2d(
            512, 1024, kernel_size=(1, 1), stride=(2, 2), bias=False
            (norm): FrozenBatchNorm2d(num_features=1024, eps=1e-05)
          )
          (conv1): Conv2d(
            512, 256, kernel_size=(1, 1), stride=(2, 2), bias=False
            (norm): FrozenBatchNorm2d(num_features=256, eps=1e-05)
          )
          (conv2): Conv2d(
            256, 256, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1), bias=False
            (norm): FrozenBatchNorm2d(num_features=256, eps=1e-05)
          )
          (conv3): Conv2d(
            256, 1024, kernel_size=(1, 1), stride=(1, 1), bias=False
            (norm): FrozenBatchNorm2d(num_features=1024, eps=1e-05)
          )
        )
        (1): BottleneckBlock(
          (conv1): Conv2d(
            1024, 256, kernel_size=(1, 1), stride=(1, 1), bias=False
            (norm): FrozenBatchNorm2d(num_features=256, eps=1e-05)
          )
          (conv2): Conv2d(
            256, 256, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1), bias=False
            (norm): FrozenBatchNorm2d(num_features=256, eps=1e-05)
          )
          (conv3): Conv2d(
            256, 1024, kernel_size=(1, 1), stride=(1, 1), bias=False
            (norm): FrozenBatchNorm2d(num_features=1024, eps=1e-05)
          )
        )
        (2): BottleneckBlock(
          (conv1): Conv2d(
            1024, 256, kernel_size=(1, 1), stride=(1, 1), bias=False
            (norm): FrozenBatchNorm2d(num_features=256, eps=1e-05)
          )
          (conv2): Conv2d(
            256, 256, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1), bias=False
            (norm): FrozenBatchNorm2d(num_features=256, eps=1e-05)
          )
          (conv3): Conv2d(
            256, 1024, kernel_size=(1, 1), stride=(1, 1), bias=False
            (norm): FrozenBatchNorm2d(num_features=1024, eps=1e-05)
          )
        )
        (3): BottleneckBlock(
          (conv1): Conv2d(
            1024, 256, kernel_size=(1, 1), stride=(1, 1), bias=False
            (norm): FrozenBatchNorm2d(num_features=256, eps=1e-05)
          )
          (conv2): Conv2d(
            256, 256, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1), bias=False
            (norm): FrozenBatchNorm2d(num_features=256, eps=1e-05)
          )
          (conv3): Conv2d(
            256, 1024, kernel_size=(1, 1), stride=(1, 1), bias=False
            (norm): FrozenBatchNorm2d(num_features=1024, eps=1e-05)
          )
        )
        (4): BottleneckBlock(
          (conv1): Conv2d(
            1024, 256, kernel_size=(1, 1), stride=(1, 1), bias=False
            (norm): FrozenBatchNorm2d(num_features=256, eps=1e-05)
          )
          (conv2): Conv2d(
            256, 256, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1), bias=False
            (norm): FrozenBatchNorm2d(num_features=256, eps=1e-05)
          )
          (conv3): Conv2d(
            256, 1024, kernel_size=(1, 1), stride=(1, 1), bias=False
            (norm): FrozenBatchNorm2d(num_features=1024, eps=1e-05)
          )
        )
        (5): BottleneckBlock(
          (conv1): Conv2d(
            1024, 256, kernel_size=(1, 1), stride=(1, 1), bias=False
            (norm): FrozenBatchNorm2d(num_features=256, eps=1e-05)
          )
          (conv2): Conv2d(
            256, 256, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1), bias=False
            (norm): FrozenBatchNorm2d(num_features=256, eps=1e-05)
          )
          (conv3): Conv2d(
            256, 1024, kernel_size=(1, 1), stride=(1, 1), bias=False
            (norm): FrozenBatchNorm2d(num_features=1024, eps=1e-05)
          )
        )
      )
      (res5): Sequential(
        (0): BottleneckBlock(
          (shortcut): Conv2d(
            1024, 2048, kernel_size=(1, 1), stride=(2, 2), bias=False
            (norm): FrozenBatchNorm2d(num_features=2048, eps=1e-05)
          )
          (conv1): Conv2d(
            1024, 512, kernel_size=(1, 1), stride=(2, 2), bias=False
            (norm): FrozenBatchNorm2d(num_features=512, eps=1e-05)
          )
          (conv2): Conv2d(
            512, 512, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1), bias=False
            (norm): FrozenBatchNorm2d(num_features=512, eps=1e-05)
          )
          (conv3): Conv2d(
            512, 2048, kernel_size=(1, 1), stride=(1, 1), bias=False
            (norm): FrozenBatchNorm2d(num_features=2048, eps=1e-05)
          )
        )
        (1): BottleneckBlock(
          (conv1): Conv2d(
            2048, 512, kernel_size=(1, 1), stride=(1, 1), bias=False
            (norm): FrozenBatchNorm2d(num_features=512, eps=1e-05)
          )
          (conv2): Conv2d(
            512, 512, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1), bias=False
            (norm): FrozenBatchNorm2d(num_features=512, eps=1e-05)
          )
          (conv3): Conv2d(
            512, 2048, kernel_size=(1, 1), stride=(1, 1), bias=False
            (norm): FrozenBatchNorm2d(num_features=2048, eps=1e-05)
          )
        )
        (2): BottleneckBlock(
          (conv1): Conv2d(
            2048, 512, kernel_size=(1, 1), stride=(1, 1), bias=False
            (norm): FrozenBatchNorm2d(num_features=512, eps=1e-05)
          )
          (conv2): Conv2d(
            512, 512, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1), bias=False
            (norm): FrozenBatchNorm2d(num_features=512, eps=1e-05)
          )
          (conv3): Conv2d(
            512, 2048, kernel_size=(1, 1), stride=(1, 1), bias=False
            (norm): FrozenBatchNorm2d(num_features=2048, eps=1e-05)
          )
        )
      )
    )
  )
  (proposal_generator): RPN(
    (rpn_head): StandardRPNHead(
      (conv): Conv2d(
        256, 256, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1)
        (activation): ReLU()
      )
      (objectness_logits): Conv2d(256, 3, kernel_size=(1, 1), stride=(1, 1))
      (anchor_deltas): Conv2d(256, 12, kernel_size=(1, 1), stride=(1, 1))
    )
    (anchor_generator): DefaultAnchorGenerator(
      (cell_anchors): BufferList()
    )
  )
  (roi_heads): StandardROIHeads(
    (box_pooler): ROIPooler(
      (level_poolers): ModuleList(
        (0): ROIAlign(output_size=(7, 7), spatial_scale=0.25, sampling_ratio=0, aligned=True)
        (1): ROIAlign(output_size=(7, 7), spatial_scale=0.125, sampling_ratio=0, aligned=True)
        (2): ROIAlign(output_size=(7, 7), spatial_scale=0.0625, sampling_ratio=0, aligned=True)
        (3): ROIAlign(output_size=(7, 7), spatial_scale=0.03125, sampling_ratio=0, aligned=True)
      )
    )
    (box_head): FastRCNNConvFCHead(
      (flatten): Flatten(start_dim=1, end_dim=-1)
      (fc1): Linear(in_features=12544, out_features=1024, bias=True)
      (fc_relu1): ReLU()
      (fc2): Linear(in_features=1024, out_features=1024, bias=True)
      (fc_relu2): ReLU()
    )
    (box_predictor): FastRCNNOutputLayers(
      (cls_score): Linear(in_features=1024, out_features=7, bias=True)
      (bbox_pred): Linear(in_features=1024, out_features=24, bias=True)
    )
  )
)
[07/16 06:29:17 d2.data.build]: Removed 0 images with no usable annotations. 423 images left.
[07/16 06:29:17 d2.data.build]: Distribution of instances among all 6 categories:
|  category  | #instances   |  category  | #instances   |  category  | #instances   |
|:----------:|:-------------|:----------:|:-------------|:----------:|:-------------|
|   person   | 194          |  bicycle   | 14           |    car     | 2803         |
| motorcycle | 11           |    bus     | 70           |   truck    | 266          |
|            |              |            |              |            |              |
|   total    | 3358         |            |              |            |              |
[07/16 06:29:17 d2.data.dataset_mapper]: [DatasetMapper] Augmentations used in training: [ResizeShortestEdge(short_edge_length=(640, 672, 704, 736, 768, 800), max_size=1333, sample_style='choice'), RandomFlip()]
[07/16 06:29:17 d2.data.build]: Using training sampler TrainingSampler
[07/16 06:29:17 d2.data.common]: Serializing the dataset using: <class 'detectron2.data.common._TorchSerializedList'>
[07/16 06:29:17 d2.data.common]: Serializing 423 elements to byte tensors and concatenating them all ...
[07/16 06:29:17 d2.data.common]: Serialized dataset takes 0.33 MiB
[07/16 06:29:17 d2.data.build]: Making batched data loader with batch_size=4
[07/16 06:29:17 d2.checkpoint.detection_checkpoint]: [DetectionCheckpointer] Loading from https://dl.fbaipublicfiles.com/detectron2/COCO-Detection/faster_rcnn_R_50_FPN_3x/137849458/model_final_280758.pkl ...

model_final_280758.pkl: 167MB [00:00, 327MB/s]
WARNING:fvcore.common.checkpoint:Skip loading parameter 'roi_heads.box_predictor.cls_score.weight' to the model due to incompatible shapes: (81, 1024) in the checkpoint but (7, 1024) in the model! You might want to double check if this is expected.
WARNING:fvcore.common.checkpoint:Skip loading parameter 'roi_heads.box_predictor.cls_score.bias' to the model due to incompatible shapes: (81,) in the checkpoint but (7,) in the model! You might want to double check if this is expected.
WARNING:fvcore.common.checkpoint:Skip loading parameter 'roi_heads.box_predictor.bbox_pred.weight' to the model due to incompatible shapes: (320, 1024) in the checkpoint but (24, 1024) in the model! You might want to double check if this is expected.
WARNING:fvcore.common.checkpoint:Skip loading parameter 'roi_heads.box_predictor.bbox_pred.bias' to the model due to incompatible shapes: (320,) in the checkpoint but (24,) in the model! You might want to double check if this is expected.
WARNING:fvcore.common.checkpoint:Some model parameters or buffers are not found in the checkpoint:
roi_heads.box_predictor.bbox_pred.{bias, weight}
roi_heads.box_predictor.cls_score.{bias, weight}

[07/16 06:29:17 d2.engine.train_loop]: Starting training from iteration 0

/usr/local/lib/python3.12/dist-packages/torch/functional.py:505: UserWarning: torch.meshgrid: in an upcoming release, it will be required to pass the indexing argument. (Triggered internally at /pytorch/aten/src/ATen/native/TensorShape.cpp:4381.)
  return _VF.meshgrid(tensors, **kwargs)  # type: ignore[attr-defined]
W0716 06:29:22.068000 3324 torch/fx/_symbolic_trace.py:53] is_fx_tracing will return true for both fx.symbolic_trace and torch.export. Please use is_fx_tracing_symbolic_tracing() for specifically fx.symbolic_trace or torch.compiler.is_compiling() for specifically torch.export/compile.

Streaming output truncated to the last 5000 lines.
 Average Recall     (AR) @[ IoU=0.50:0.95 | area=   all | maxDets= 10 ] = 0.067
 Average Recall     (AR) @[ IoU=0.50:0.95 | area=   all | maxDets=100 ] = 0.091
 Average Recall     (AR) @[ IoU=0.50:0.95 | area= small | maxDets=100 ] = 0.041
 Average Recall     (AR) @[ IoU=0.50:0.95 | area=medium | maxDets=100 ] = 0.081
 Average Recall     (AR) @[ IoU=0.50:0.95 | area= large | maxDets=100 ] = 0.146
[07/16 06:34:36 d2.evaluation.coco_evaluation]: Evaluation results for bbox:
|  AP   |  AP50  |  AP75  |  APs  |  APm  |  APl   |
|:-----:|:------:|:------:|:-----:|:-----:|:------:|
| 8.159 | 12.316 | 8.998  | 3.327 | 7.140 | 13.404 |
[07/16 06:34:36 d2.evaluation.coco_evaluation]: Per-category bbox AP:
| category   | AP    | category   | AP    | category   | AP     |
|:-----------|:------|:-----------|:------|:-----------|:-------|
| person     | 0.000 | bicycle    | 0.000 | car        | 48.954 |
| motorcycle | 0.000 | bus        | 0.000 | truck      | 0.000  |
[07/16 06:34:36 d2.engine.defaults]: Evaluation results for dawn_val in csv format:
[07/16 06:34:36 d2.evaluation.testing]: copypaste: Task: bbox
[07/16 06:34:36 d2.evaluation.testing]: copypaste: AP,AP50,AP75,APs,APm,APl
[07/16 06:34:36 d2.evaluation.testing]: copypaste: 8.1591,12.3163,8.9984,3.3265,7.1403,13.4037
[07/16 06:34:36 d2.engine.hooks]: Saved best model as latest eval score for bbox/AP is 8.15905, better than last best score 6.87950 @ iteration 211.
[07/16 06:34:37 d2.utils.events]:  eta: 0:30:51  iter: 319  total_loss: 0.5363  loss_cls: 0.1946  loss_box_reg: 0.2893  loss_rpn_cls: 0.01372  loss_rpn_loc: 0.02611    time: 0.7076  last_time: 0.1795  data_time: 0.0111  last_data_time: 0.0107   lr: 0.00031968  max_mem: 4231M
[07/16 06:34:40 d2.utils.events]:  eta: 0:30:44  iter: 339  total_loss: 0.566  loss_cls: 0.2186  loss_box_reg: 0.3142  loss_rpn_cls: 0.01624  loss_rpn_loc: 0.02541    time: 0.6762  last_time: 0.1755  data_time: 0.0116  last_data_time: 0.0089   lr: 0.00033966  max_mem: 4231M
[07/16 06:34:44 d2.utils.events]:  eta: 0:30:34  iter: 359  total_loss: 0.587  loss_cls: 0.225  loss_box_reg: 0.295  loss_rpn_cls: 0.01507  loss_rpn_loc: 0.02017    time: 0.6480  last_time: 0.1813  data_time: 0.0106  last_data_time: 0.0179   lr: 0.00035964  max_mem: 4231M
[07/16 06:34:51 d2.utils.events]:  eta: 0:30:28  iter: 379  total_loss: 0.6227  loss_cls: 0.2246  loss_box_reg: 0.3216  loss_rpn_cls: 0.01362  loss_rpn_loc: 0.03073    time: 0.6336  last_time: 0.1982  data_time: 0.2124  last_data_time: 0.0387   lr: 0.00037962  max_mem: 4231M
[07/16 06:34:55 d2.utils.events]:  eta: 0:30:21  iter: 399  total_loss: 0.6542  loss_cls: 0.2383  loss_box_reg: 0.3345  loss_rpn_cls: 0.01988  loss_rpn_loc: 0.03298    time: 0.6109  last_time: 0.1729  data_time: 0.0201  last_data_time: 0.0099   lr: 0.0003996  max_mem: 4231M
[07/16 06:34:58 d2.utils.events]:  eta: 0:30:15  iter: 419  total_loss: 0.5441  loss_cls: 0.1954  loss_box_reg: 0.3166  loss_rpn_cls: 0.01837  loss_rpn_loc: 0.0223    time: 0.5902  last_time: 0.1773  data_time: 0.0165  last_data_time: 0.0120   lr: 0.00041958  max_mem: 4231M
[07/16 06:34:59 d2.data.dataset_mapper]: [DatasetMapper] Augmentations used in inference: [ResizeShortestEdge(short_edge_length=(800, 800), max_size=1333, sample_style='choice')]
[07/16 06:34:59 d2.data.common]: Serializing the dataset using: <class 'detectron2.data.common._TorchSerializedList'>
[07/16 06:34:59 d2.data.common]: Serializing 140 elements to byte tensors and concatenating them all ...
[07/16 06:34:59 d2.data.common]: Serialized dataset takes 0.12 MiB
WARNING [07/16 06:34:59 d2.evaluation.coco_evaluation]: COCO Evaluator instantiated using config, this is deprecated behavior. Please pass in explicit arguments instead.
[07/16 06:34:59 d2.evaluation.evaluator]: Start inference on 140 batches
[07/16 06:35:00 d2.evaluation.evaluator]: Inference done 11/140. Dataloading: 0.0024 s/iter. Inference: 0.0279 s/iter. Eval: 0.0003 s/iter. Total: 0.0305 s/iter. ETA=0:00:03
[07/16 06:35:04 d2.evaluation.evaluator]: Total inference time: 0:00:04.057799 (0.030058 s / iter per device, on 1 devices)
[07/16 06:35:04 d2.evaluation.evaluator]: Total inference pure compute time: 0:00:03 (0.027038 s / iter per device, on 1 devices)
[07/16 06:35:04 d2.evaluation.coco_evaluation]: Preparing results for COCO format ...
[07/16 06:35:04 d2.evaluation.coco_evaluation]: Saving results to /content/drive/MyDrive/Dissertation/Runs/faster_rcnn/dawn_indomain_fasterrcnn_r50fpn_seed456/eval/dawn_val/coco_instances_results.json
[07/16 06:35:04 d2.evaluation.coco_evaluation]: Evaluating predictions with unofficial COCO API...
Loading and preparing results...
DONE (t=0.00s)
creating index...
index created!
[07/16 06:35:04 d2.evaluation.fast_eval_api]: Evaluate annotation type *bbox*
[07/16 06:35:04 d2.evaluation.fast_eval_api]: COCOeval_opt.evaluate() finished in 0.03 seconds.
[07/16 06:35:04 d2.evaluation.fast_eval_api]: Accumulating evaluation results...
[07/16 06:35:04 d2.evaluation.fast_eval_api]: COCOeval_opt.accumulate() finished in 0.02 seconds.
 Average Precision  (AP) @[ IoU=0.50:0.95 | area=   all | maxDets=100 ] = 0.088
 Average Precision  (AP) @[ IoU=0.50      | area=   all | maxDets=100 ] = 0.136
 Average Precision  (AP) @[ IoU=0.75      | area=   all | maxDets=100 ] = 0.099
 Average Precision  (AP) @[ IoU=0.50:0.95 | area= small | maxDets=100 ] = 0.042
 Average Precision  (AP) @[ IoU=0.50:0.95 | area=medium | maxDets=100 ] = 0.077
 Average Precision  (AP) @[ IoU=0.50:0.95 | area= large | maxDets=100 ] = 0.144
 Average Recall     (AR) @[ IoU=0.50:0.95 | area=   all | maxDets=  1 ] = 0.020
 Average Recall     (AR) @[ IoU=0.50:0.95 | area=   all | maxDets= 10 ] = 0.073
 Average Recall     (AR) @[ IoU=0.50:0.95 | area=   all | maxDets=100 ] = 0.097
 Average Recall     (AR) @[ IoU=0.50:0.95 | area= small | maxDets=100 ] = 0.051
 Average Recall     (AR) @[ IoU=0.50:0.95 | area=medium | maxDets=100 ] = 0.086
 Average Recall     (AR) @[ IoU=0.50:0.95 | area= large | maxDets=100 ] = 0.155
[07/16 06:35:04 d2.evaluation.coco_evaluation]: Evaluation results for bbox:
|  AP   |  AP50  |  AP75  |  APs  |  APm  |  APl   |
|:-----:|:------:|:------:|:-----:|:-----:|:------:|
| 8.845 | 13.606 | 9.913  | 4.219 | 7.652 | 14.424 |
[07/16 06:35:04 d2.evaluation.coco_evaluation]: Per-category bbox AP:
| category   | AP    | category   | AP    | category   | AP     |
|:-----------|:------|:-----------|:------|:-----------|:-------|
| person     | 0.000 | bicycle    | 0.000 | car        | 50.599 |
| motorcycle | 0.000 | bus        | 0.000 | truck      | 2.472  |
[07/16 06:35:04 d2.engine.defaults]: Evaluation results for dawn_val in csv format:
[07/16 06:35:04 d2.evaluation.testing]: copypaste: Task: bbox
[07/16 06:35:04 d2.evaluation.testing]: copypaste: AP,AP50,AP75,APs,APm,APl
[07/16 06:35:04 d2.evaluation.testing]: copypaste: 8.8451,13.6061,9.9126,4.2188,7.6523,14.4236
[07/16 06:35:04 d2.engine.hooks]: Saved best model as latest eval score for bbox/AP is 8.84513, better than last best score 8.15905 @ iteration 317.
[07/16 06:35:08 d2.utils.events]:  eta: 0:30:07  iter: 439  total_loss: 0.5654  loss_cls: 0.2174  loss_box_reg: 0.3016  loss_rpn_cls: 0.02016  loss_rpn_loc: 0.02632    time: 0.5721  last_time: 0.1777  data_time: 0.0319  last_data_time: 0.0098   lr: 0.00043956  max_mem: 4231M
[07/16 06:35:11 d2.utils.events]:  eta: 0:29:59  iter: 459  total_loss: 0.5366  loss_cls: 0.2083  loss_box_reg: 0.3037  loss_rpn_cls: 0.007359  loss_rpn_loc: 0.01887    time: 0.5548  last_time: 0.1791  data_time: 0.0132  last_data_time: 0.0101   lr: 0.00045954  max_mem: 4231M
[07/16 06:35:18 d2.utils.events]:  eta: 0:29:55  iter: 479  total_loss: 0.5277  loss_cls: 0.1907  loss_box_reg: 0.2799  loss_rpn_cls: 0.01403  loss_rpn_loc: 0.02608    time: 0.5470  last_time: 0.1812  data_time: 0.2045  last_data_time: 0.0098   lr: 0.00047952  max_mem: 4231M
[07/16 06:35:22 d2.utils.events]:  eta: 0:29:48  iter: 499  total_loss: 0.5345  loss_cls: 0.2079  loss_box_reg: 0.2985  loss_rpn_cls: 0.009177  loss_rpn_loc: 0.02838    time: 0.5320  last_time: 0.1566  data_time: 0.0130  last_data_time: 0.0098   lr: 0.0004995  max_mem: 4231M
[07/16 06:35:26 d2.utils.events]:  eta: 0:29:43  iter: 519  total_loss: 0.5301  loss_cls: 0.1967  loss_box_reg: 0.2948  loss_rpn_cls: 0.01037  loss_rpn_loc: 0.02854    time: 0.5186  last_time: 0.1706  data_time: 0.0180  last_data_time: 0.0085   lr: 0.00051948  max_mem: 4231M
[07/16 06:35:28 d2.data.dataset_mapper]: [DatasetMapper] Augmentations used in inference: [ResizeShortestEdge(short_edge_length=(800, 800), max_size=1333, sample_style='choice')]
[07/16 06:35:28 d2.data.common]: Serializing the dataset using: <class 'detectron2.data.common._TorchSerializedList'>
[07/16 06:35:28 d2.data.common]: Serializing 140 elements to byte tensors and concatenating them all ...
[07/16 06:35:28 d2.data.common]: Serialized dataset takes 0.12 MiB
WARNING [07/16 06:35:28 d2.evaluation.coco_evaluation]: COCO Evaluator instantiated using config, this is deprecated behavior. Please pass in explicit arguments instead.
[07/16 06:35:28 d2.evaluation.evaluator]: Start inference on 140 batches
[07/16 06:35:28 d2.evaluation.evaluator]: Inference done 11/140. Dataloading: 0.0015 s/iter. Inference: 0.0282 s/iter. Eval: 0.0003 s/iter. Total: 0.0300 s/iter. ETA=0:00:03
[07/16 06:35:32 d2.evaluation.evaluator]: Total inference time: 0:00:04.155403 (0.030781 s / iter per device, on 1 devices)
[07/16 06:35:32 d2.evaluation.evaluator]: Total inference pure compute time: 0:00:03 (0.027162 s / iter per device, on 1 devices)
[07/16 06:35:32 d2.evaluation.coco_evaluation]: Preparing results for COCO format ...
[07/16 06:35:32 d2.evaluation.coco_evaluation]: Saving results to /content/drive/MyDrive/Dissertation/Runs/faster_rcnn/dawn_indomain_fasterrcnn_r50fpn_seed456/eval/dawn_val/coco_instances_results.json
[07/16 06:35:32 d2.evaluation.coco_evaluation]: Evaluating predictions with unofficial COCO API...
Loading and preparing results...
DONE (t=0.00s)
creating index...
index created!
[07/16 06:35:32 d2.evaluation.fast_eval_api]: Evaluate annotation type *bbox*
[07/16 06:35:32 d2.evaluation.fast_eval_api]: COCOeval_opt.evaluate() finished in 0.03 seconds.
[07/16 06:35:32 d2.evaluation.fast_eval_api]: Accumulating evaluation results...
[07/16 06:35:32 d2.evaluation.fast_eval_api]: COCOeval_opt.accumulate() finished in 0.02 seconds.
 Average Precision  (AP) @[ IoU=0.50:0.95 | area=   all | maxDets=100 ] = 0.110
 Average Precision  (AP) @[ IoU=0.50      | area=   all | maxDets=100 ] = 0.177
 Average Precision  (AP) @[ IoU=0.75      | area=   all | maxDets=100 ] = 0.120
 Average Precision  (AP) @[ IoU=0.50:0.95 | area= small | maxDets=100 ] = 0.046
 Average Precision  (AP) @[ IoU=0.50:0.95 | area=medium | maxDets=100 ] = 0.099
 Average Precision  (AP) @[ IoU=0.50:0.95 | area= large | maxDets=100 ] = 0.171
 Average Recall     (AR) @[ IoU=0.50:0.95 | area=   all | maxDets=  1 ] = 0.032
 Average Recall     (AR) @[ IoU=0.50:0.95 | area=   all | maxDets= 10 ] = 0.099
 Average Recall     (AR) @[ IoU=0.50:0.95 | area=   all | maxDets=100 ] = 0.125
 Average Recall     (AR) @[ IoU=0.50:0.95 | area= small | maxDets=100 ] = 0.055
 Average Recall     (AR) @[ IoU=0.50:0.95 | area=medium | maxDets=100 ] = 0.115
 Average Recall     (AR) @[ IoU=0.50:0.95 | area= large | maxDets=100 ] = 0.188
[07/16 06:35:32 d2.evaluation.coco_evaluation]: Evaluation results for bbox:
|   AP   |  AP50  |  AP75  |  APs  |  APm  |  APl   |
|:------:|:------:|:------:|:-----:|:-----:|:------:|
| 10.998 | 17.706 | 11.991 | 4.553 | 9.866 | 17.109 |
[07/16 06:35:32 d2.evaluation.coco_evaluation]: Per-category bbox AP:
| category   | AP    | category   | AP    | category   | AP     |
|:-----------|:------|:-----------|:------|:-----------|:-------|
| person     | 0.000 | bicycle    | 0.000 | car        | 50.885 |
| motorcycle | 0.000 | bus        | 0.000 | truck      | 15.102 |
[07/16 06:35:32 d2.engine.defaults]: Evaluation results for dawn_val in csv format:
[07/16 06:35:32 d2.evaluation.testing]: copypaste: Task: bbox
[07/16 06:35:32 d2.evaluation.testing]: copypaste: AP,AP50,AP75,APs,APm,APl
[07/16 06:35:32 d2.evaluation.testing]: copypaste: 10.9978,17.7057,11.9905,4.5527,9.8658,17.1089
[07/16 06:35:33 d2.engine.hooks]: Saved best model as latest eval score for bbox/AP is 10.99780, better than last best score 8.84513 @ iteration 423.
[07/16 06:35:35 d2.utils.events]:  eta: 0:29:38  iter: 539  total_loss: 0.5373  loss_cls: 0.2011  loss_box_reg: 0.3161  loss_rpn_cls: 0.01289  loss_rpn_loc: 0.03292    time: 0.5063  last_time: 0.1718  data_time: 0.0208  last_data_time: 0.0084   lr: 0.00053946  max_mem: 4231M
[07/16 06:35:38 d2.utils.events]:  eta: 0:29:32  iter: 559  total_loss: 0.5825  loss_cls: 0.2029  loss_box_reg: 0.3166  loss_rpn_cls: 0.01196  loss_rpn_loc: 0.02763    time: 0.4943  last_time: 0.1813  data_time: 0.0122  last_data_time: 0.0101   lr: 0.00055944  max_mem: 4232M
[07/16 06:35:42 d2.utils.events]:  eta: 0:29:27  iter: 579  total_loss: 0.5141  loss_cls: 0.1889  loss_box_reg: 0.2822  loss_rpn_cls: 0.01021  loss_rpn_loc: 0.02367    time: 0.4834  last_time: 0.1724  data_time: 0.0168  last_data_time: 0.0085   lr: 0.00057942  max_mem: 4232M
[07/16 06:35:49 d2.utils.events]:  eta: 0:29:24  iter: 599  total_loss: 0.4618  loss_cls: 0.1876  loss_box_reg: 0.2516  loss_rpn_cls: 0.0107  loss_rpn_loc: 0.01587    time: 0.4799  last_time: 0.1759  data_time: 0.2083  last_data_time: 0.0098   lr: 0.0005994  max_mem: 4232M
[07/16 06:35:53 d2.utils.events]:  eta: 0:29:21  iter: 619  total_loss: 0.6149  loss_cls: 0.2163  loss_box_reg: 0.3374  loss_rpn_cls: 0.01437  loss_rpn_loc: 0.02851    time: 0.4702  last_time: 0.1802  data_time: 0.0131  last_data_time: 0.0090   lr: 0.00061938  max_mem: 4232M
[07/16 06:35:56 d2.data.dataset_mapper]: [DatasetMapper] Augmentations used in inference: [ResizeShortestEdge(short_edge_length=(800, 800), max_size=1333, sample_style='choice')]
[07/16 06:35:56 d2.data.common]: Serializing the dataset using: <class 'detectron2.data.common._TorchSerializedList'>
[07/16 06:35:56 d2.data.common]: Serializing 140 elements to byte tensors and concatenating them all ...
[07/16 06:35:56 d2.data.common]: Serialized dataset takes 0.12 MiB
WARNING [07/16 06:35:56 d2.evaluation.coco_evaluation]: COCO Evaluator instantiated using config, this is deprecated behavior. Please pass in explicit arguments instead.
[07/16 06:35:56 d2.evaluation.evaluator]: Start inference on 140 batches
[07/16 06:35:57 d2.evaluation.evaluator]: Inference done 11/140. Dataloading: 0.0014 s/iter. Inference: 0.0276 s/iter. Eval: 0.0003 s/iter. Total: 0.0293 s/iter. ETA=0:00:03
[07/16 06:36:01 d2.evaluation.evaluator]: Total inference time: 0:00:04.475691 (0.033153 s / iter per device, on 1 devices)
[07/16 06:36:01 d2.evaluation.evaluator]: Total inference pure compute time: 0:00:04 (0.030307 s / iter per device, on 1 devices)
[07/16 06:36:01 d2.evaluation.coco_evaluation]: Preparing results for COCO format ...
[07/16 06:36:01 d2.evaluation.coco_evaluation]: Saving results to /content/drive/MyDrive/Dissertation/Runs/faster_rcnn/dawn_indomain_fasterrcnn_r50fpn_seed456/eval/dawn_val/coco_instances_results.json
[07/16 06:36:01 d2.evaluation.coco_evaluation]: Evaluating predictions with unofficial COCO API...
Loading and preparing results...
DONE (t=0.00s)
creating index...
index created!
[07/16 06:36:01 d2.evaluation.fast_eval_api]: Evaluate annotation type *bbox*
[07/16 06:36:01 d2.evaluation.fast_eval_api]: COCOeval_opt.evaluate() finished in 0.03 seconds.
[07/16 06:36:01 d2.evaluation.fast_eval_api]: Accumulating evaluation results...
[07/16 06:36:01 d2.evaluation.fast_eval_api]: COCOeval_opt.accumulate() finished in 0.02 seconds.
 Average Precision  (AP) @[ IoU=0.50:0.95 | area=   all | maxDets=100 ] = 0.164
 Average Precision  (AP) @[ IoU=0.50      | area=   all | maxDets=100 ] = 0.271
 Average Precision  (AP) @[ IoU=0.75      | area=   all | maxDets=100 ] = 0.166
 Average Precision  (AP) @[ IoU=0.50:0.95 | area= small | maxDets=100 ] = 0.054
 Average Precision  (AP) @[ IoU=0.50:0.95 | area=medium | maxDets=100 ] = 0.149
 Average Precision  (AP) @[ IoU=0.50:0.95 | area= large | maxDets=100 ] = 0.254
 Average Recall     (AR) @[ IoU=0.50:0.95 | area=   all | maxDets=  1 ] = 0.070
 Average Recall     (AR) @[ IoU=0.50:0.95 | area=   all | maxDets= 10 ] = 0.162
 Average Recall     (AR) @[ IoU=0.50:0.95 | area=   all | maxDets=100 ] = 0.190
 Average Recall     (AR) @[ IoU=0.50:0.95 | area= small | maxDets=100 ] = 0.066
 Average Recall     (AR) @[ IoU=0.50:0.95 | area=medium | maxDets=100 ] = 0.181
 Average Recall     (AR) @[ IoU=0.50:0.95 | area= large | maxDets=100 ] = 0.282
[07/16 06:36:01 d2.evaluation.coco_evaluation]: Evaluation results for bbox:
|   AP   |  AP50  |  AP75  |  APs  |  APm   |  APl   |
|:------:|:------:|:------:|:-----:|:------:|:------:|
| 16.357 | 27.135 | 16.640 | 5.355 | 14.913 | 25.352 |
[07/16 06:36:01 d2.evaluation.coco_evaluation]: Per-category bbox AP:
| category   | AP     | category   | AP    | category   | AP     |
|:-----------|:-------|:-----------|:------|:-----------|:-------|
| person     | 16.185 | bicycle    | 0.000 | car        | 53.743 |
| motorcycle | 0.000  | bus        | 0.000 | truck      | 28.215 |
[07/16 06:36:01 d2.engine.defaults]: Evaluation results for dawn_val in csv format:
[07/16 06:36:01 d2.evaluation.testing]: copypaste: Task: bbox
[07/16 06:36:01 d2.evaluation.testing]: copypaste: AP,AP50,AP75,APs,APm,APl
[07/16 06:36:01 d2.evaluation.testing]: copypaste: 16.3573,27.1352,16.6404,5.3546,14.9129,25.3516
[07/16 06:36:01 d2.engine.hooks]: Saved best model as latest eval score for bbox/AP is 16.35725, better than last best score 10.99780 @ iteration 529.
[07/16 06:36:02 d2.utils.events]:  eta: 0:29:14  iter: 639  total_loss: 0.5318  loss_cls: 0.2013  loss_box_reg: 0.3013  loss_rpn_cls: 0.005592  loss_rpn_loc: 0.02117    time: 0.4610  last_time: 0.1776  data_time: 0.0147  last_data_time: 0.0102   lr: 0.00063936  max_mem: 4232M
[07/16 06:36:06 d2.utils.events]:  eta: 0:29:09  iter: 659  total_loss: 0.4725  loss_cls: 0.165  loss_box_reg: 0.2748  loss_rpn_cls: 0.009258  loss_rpn_loc: 0.01968    time: 0.4524  last_time: 0.1782  data_time: 0.0186  last_data_time: 0.0085   lr: 0.00065934  max_mem: 4232M
[07/16 06:36:09 d2.utils.events]:  eta: 0:29:05  iter: 679  total_loss: 0.5338  loss_cls: 0.205  loss_box_reg: 0.2967  loss_rpn_cls: 0.009311  loss_rpn_loc: 0.02483    time: 0.4443  last_time: 0.1856  data_time: 0.0121  last_data_time: 0.0105   lr: 0.00067932  max_mem: 4232M
[07/16 06:36:13 d2.utils.events]:  eta: 0:29:02  iter: 699  total_loss: 0.5374  loss_cls: 0.2015  loss_box_reg: 0.2977  loss_rpn_cls: 0.01138  loss_rpn_loc: 0.0258    time: 0.4366  last_time: 0.1677  data_time: 0.0108  last_data_time: 0.0085   lr: 0.0006993  max_mem: 4232M
[07/16 06:36:20 d2.utils.events]:  eta: 0:28:57  iter: 719  total_loss: 0.4815  loss_cls: 0.1859  loss_box_reg: 0.2606  loss_rpn_cls: 0.007686  loss_rpn_loc: 0.02534    time: 0.4347  last_time: 0.1810  data_time: 0.2054  last_data_time: 0.0106   lr: 0.00071928  max_mem: 4232M
[07/16 06:36:24 d2.utils.events]:  eta: 0:28:52  iter: 739  total_loss: 0.5432  loss_cls: 0.1965  loss_box_reg: 0.2863  loss_rpn_cls: 0.01018  loss_rpn_loc: 0.02494    time: 0.4279  last_time: 0.1731  data_time: 0.0172  last_data_time: 0.0101   lr: 0.00073926  max_mem: 4232M
[07/16 06:36:25 d2.data.dataset_mapper]: [DatasetMapper] Augmentations used in inference: [ResizeShortestEdge(short_edge_length=(800, 800), max_size=1333, sample_style='choice')]
[07/16 06:36:25 d2.data.common]: Serializing the dataset using: <class 'detectron2.data.common._TorchSerializedList'>
[07/16 06:36:25 d2.data.common]: Serializing 140 elements to byte tensors and concatenating them all ...
[07/16 06:36:25 d2.data.common]: Serialized dataset takes 0.12 MiB

### **Load best model**

In [18]:
BEST_MODEL = OUTPUT_DIR / "model_best.pth"

print("Best model exists:", BEST_MODEL.exists())

cfg.MODEL.WEIGHTS = str(BEST_MODEL)
cfg.MODEL.ROI_HEADS.SCORE_THRESH_TEST = 0.5

predictor = DefaultPredictor(cfg)

Best model exists: True
[07/16 09:54:23 d2.checkpoint.detection_checkpoint]: [DetectionCheckpointer] Loading from /content/drive/MyDrive/Dissertation/Runs/faster_rcnn/dawn_indomain_fasterrcnn_r50fpn_seed456/model_best.pth ...

# **Evaluation Global and weather-specific**

In [19]:
eval_datasets = {
    "fog": "dawn_test_fog",
    "rain": "dawn_test_rain",
    "snow": "dawn_test_snow",
}

results_rows = []

for condition, dataset_name in eval_datasets.items():
    print(f"\nEvaluating DAWN {condition.upper()}...")

    evaluator = COCOEvaluator(
        dataset_name,
        cfg,
        False,
        output_dir=str(OUTPUT_DIR / "evaluation" / condition)
    )

    loader = build_detection_test_loader(cfg, dataset_name)
    eval_results = inference_on_dataset(predictor.model, loader, evaluator)

    bbox = eval_results["bbox"]

    results_rows.append({
        "dataset": "DAWN",
        "model": "Faster R-CNN",
        "experiment": "in_domain",
        "seed": RANDOM_SEED,
        "condition": condition,
        "mAP50-95": bbox["AP"] / 100,
        "mAP50": bbox["AP50"] / 100,
        "mAP75": bbox["AP75"] / 100,
    })

results_df = pd.DataFrame(results_rows)

global_row = {
    "dataset": "DAWN",
    "model": "Faster R-CNN",
    "experiment": "in_domain",
    "seed": RANDOM_SEED,
    "condition": "global",
    "mAP50-95": results_df["mAP50-95"].mean(),
    "mAP50": results_df["mAP50"].mean(),
    "mAP75": results_df["mAP75"].mean(),
}

results_df = pd.concat(
    [pd.DataFrame([global_row]), results_df],
    ignore_index=True
)

results_df

Evaluating DAWN FOG...
WARNING [07/16 09:54:35 d2.evaluation.coco_evaluation]: COCO Evaluator instantiated using config, this is deprecated behavior. Please pass in explicit arguments instead.
[07/16 09:54:35 d2.evaluation.coco_evaluation]: Trying to convert 'dawn_test_fog' to COCO format ...
WARNING [07/16 09:54:37 d2.data.datasets.coco]: Using previously cached COCO format annotations at '/content/drive/MyDrive/Dissertation/Runs/faster_rcnn/dawn_indomain_fasterrcnn_r50fpn_seed456/evaluation/fog/dawn_test_fog_coco_format.json'. You need to clear the cache file if your dataset has been modified.
[07/16 09:54:37 d2.data.build]: Distribution of instances among all 6 categories:
|  category  | #instances   |  category  | #instances   |  category  | #instances   |
|:----------:|:-------------|:----------:|:-------------|:----------:|:-------------|
|   person   | 15           |  bicycle   | 0            |    car     | 357          |
| motorcycle | 3            |    bus     | 11           |   truck    | 26           |
|            |              |            |              |            |              |
|   total    | 412          |            |              |            |              |
[07/16 09:54:37 d2.data.dataset_mapper]: [DatasetMapper] Augmentations used in inference: [ResizeShortestEdge(short_edge_length=(800, 800), max_size=1333, sample_style='choice')]
[07/16 09:54:37 d2.data.common]: Serializing the dataset using: <class 'detectron2.data.common._TorchSerializedList'>
[07/16 09:54:37 d2.data.common]: Serializing 60 elements to byte tensors and concatenating them all ...
[07/16 09:54:37 d2.data.common]: Serialized dataset takes 0.04 MiB
[07/16 09:54:37 d2.evaluation.evaluator]: Start inference on 60 batches

/usr/local/lib/python3.12/dist-packages/torch/functional.py:505: UserWarning: torch.meshgrid: in an upcoming release, it will be required to pass the indexing argument. (Triggered internally at /pytorch/aten/src/ATen/native/TensorShape.cpp:4381.)
  return _VF.meshgrid(tensors, **kwargs)  # type: ignore[attr-defined]
W0716 09:54:40.087000 2884 torch/fx/_symbolic_trace.py:53] is_fx_tracing will return true for both fx.symbolic_trace and torch.export. Please use is_fx_tracing_symbolic_tracing() for specifically fx.symbolic_trace or torch.compiler.is_compiling() for specifically torch.export/compile.

[07/16 09:54:43 d2.evaluation.evaluator]: Inference done 11/60. Dataloading: 0.2485 s/iter. Inference: 0.0625 s/iter. Eval: 0.0003 s/iter. Total: 0.3112 s/iter. ETA=0:00:15
[07/16 09:54:48 d2.evaluation.evaluator]: Inference done 22/60. Dataloading: 0.3680 s/iter. Inference: 0.0469 s/iter. Eval: 0.0003 s/iter. Total: 0.4152 s/iter. ETA=0:00:15
[07/16 09:54:54 d2.evaluation.evaluator]: Inference done 36/60. Dataloading: 0.3565 s/iter. Inference: 0.0439 s/iter. Eval: 0.0003 s/iter. Total: 0.4008 s/iter. ETA=0:00:09
[07/16 09:54:59 d2.evaluation.evaluator]: Inference done 49/60. Dataloading: 0.3541 s/iter. Inference: 0.0418 s/iter. Eval: 0.0003 s/iter. Total: 0.3962 s/iter. ETA=0:00:04
[07/16 09:55:03 d2.evaluation.evaluator]: Total inference time: 0:00:22.071854 (0.401306 s / iter per device, on 1 devices)
[07/16 09:55:03 d2.evaluation.evaluator]: Total inference pure compute time: 0:00:02 (0.040463 s / iter per device, on 1 devices)
[07/16 09:55:04 d2.evaluation.coco_evaluation]: Preparing results for COCO format ...
[07/16 09:55:04 d2.evaluation.coco_evaluation]: Saving results to /content/drive/MyDrive/Dissertation/Runs/faster_rcnn/dawn_indomain_fasterrcnn_r50fpn_seed456/evaluation/fog/coco_instances_results.json
[07/16 09:55:05 d2.evaluation.coco_evaluation]: Evaluating predictions with unofficial COCO API...
Loading and preparing results...
DONE (t=0.00s)
creating index...
index created!
[07/16 09:55:05 d2.evaluation.fast_eval_api]: Evaluate annotation type *bbox*
[07/16 09:55:05 d2.evaluation.fast_eval_api]: COCOeval_opt.evaluate() finished in 0.02 seconds.
[07/16 09:55:05 d2.evaluation.fast_eval_api]: Accumulating evaluation results...
[07/16 09:55:05 d2.evaluation.fast_eval_api]: COCOeval_opt.accumulate() finished in 0.02 seconds.
 Average Precision  (AP) @[ IoU=0.50:0.95 | area=   all | maxDets=100 ] = 0.380
 Average Precision  (AP) @[ IoU=0.50      | area=   all | maxDets=100 ] = 0.623
 Average Precision  (AP) @[ IoU=0.75      | area=   all | maxDets=100 ] = 0.358
 Average Precision  (AP) @[ IoU=0.50:0.95 | area= small | maxDets=100 ] = 0.400
 Average Precision  (AP) @[ IoU=0.50:0.95 | area=medium | maxDets=100 ] = 0.327
 Average Precision  (AP) @[ IoU=0.50:0.95 | area= large | maxDets=100 ] = 0.572
 Average Recall     (AR) @[ IoU=0.50:0.95 | area=   all | maxDets=  1 ] = 0.289
 Average Recall     (AR) @[ IoU=0.50:0.95 | area=   all | maxDets= 10 ] = 0.424
 Average Recall     (AR) @[ IoU=0.50:0.95 | area=   all | maxDets=100 ] = 0.441
 Average Recall     (AR) @[ IoU=0.50:0.95 | area= small | maxDets=100 ] = 0.435
 Average Recall     (AR) @[ IoU=0.50:0.95 | area=medium | maxDets=100 ] = 0.377
 Average Recall     (AR) @[ IoU=0.50:0.95 | area= large | maxDets=100 ] = 0.601
[07/16 09:55:05 d2.evaluation.coco_evaluation]: Evaluation results for bbox:
|   AP   |  AP50  |  AP75  |  APs   |  APm   |  APl   |
|:------:|:------:|:------:|:------:|:------:|:------:|
| 38.035 | 62.289 | 35.846 | 39.955 | 32.746 | 57.246 |
[07/16 09:55:05 d2.evaluation.coco_evaluation]: Per-category bbox AP:
| category   | AP     | category   | AP     | category   | AP     |
|:-----------|:-------|:-----------|:-------|:-----------|:-------|
| person     | 52.968 | bicycle    | nan    | car        | 52.834 |
| motorcycle | 31.584 | bus        | 16.040 | truck      | 36.750 |

Evaluating DAWN RAIN...
WARNING [07/16 09:55:05 d2.evaluation.coco_evaluation]: COCO Evaluator instantiated using config, this is deprecated behavior. Please pass in explicit arguments instead.
[07/16 09:55:05 d2.evaluation.coco_evaluation]: Trying to convert 'dawn_test_rain' to COCO format ...
WARNING [07/16 09:55:05 d2.data.datasets.coco]: Using previously cached COCO format annotations at '/content/drive/MyDrive/Dissertation/Runs/faster_rcnn/dawn_indomain_fasterrcnn_r50fpn_seed456/evaluation/rain/dawn_test_rain_coco_format.json'. You need to clear the cache file if your dataset has been modified.
[07/16 09:55:06 d2.data.build]: Distribution of instances among all 6 categories:
|  category  | #instances   |  category  | #instances   |  category  | #instances   |
|:----------:|:-------------|:----------:|:-------------|:----------:|:-------------|
|   person   | 5            |  bicycle   | 0            |    car     | 224          |
| motorcycle | 0            |    bus     | 2            |   truck    | 19           |
|            |              |            |              |            |              |
|   total    | 250          |            |              |            |              |
[07/16 09:55:06 d2.data.dataset_mapper]: [DatasetMapper] Augmentations used in inference: [ResizeShortestEdge(short_edge_length=(800, 800), max_size=1333, sample_style='choice')]
[07/16 09:55:06 d2.data.common]: Serializing the dataset using: <class 'detectron2.data.common._TorchSerializedList'>
[07/16 09:55:06 d2.data.common]: Serializing 40 elements to byte tensors and concatenating them all ...
[07/16 09:55:06 d2.data.common]: Serialized dataset takes 0.03 MiB
[07/16 09:55:06 d2.evaluation.evaluator]: Start inference on 40 batches
[07/16 09:55:10 d2.evaluation.evaluator]: Inference done 11/40. Dataloading: 0.3353 s/iter. Inference: 0.0301 s/iter. Eval: 0.0003 s/iter. Total: 0.3658 s/iter. ETA=0:00:10
[07/16 09:55:16 d2.evaluation.evaluator]: Inference done 24/40. Dataloading: 0.3876 s/iter. Inference: 0.0389 s/iter. Eval: 0.0003 s/iter. Total: 0.4269 s/iter. ETA=0:00:06
[07/16 09:55:21 d2.evaluation.evaluator]: Inference done 36/40. Dataloading: 0.3907 s/iter. Inference: 0.0367 s/iter. Eval: 0.0003 s/iter. Total: 0.4278 s/iter. ETA=0:00:01
[07/16 09:55:23 d2.evaluation.evaluator]: Total inference time: 0:00:14.855932 (0.424455 s / iter per device, on 1 devices)
[07/16 09:55:23 d2.evaluation.evaluator]: Total inference pure compute time: 0:00:01 (0.035857 s / iter per device, on 1 devices)
[07/16 09:55:24 d2.evaluation.coco_evaluation]: Preparing results for COCO format ...
[07/16 09:55:24 d2.evaluation.coco_evaluation]: Saving results to /content/drive/MyDrive/Dissertation/Runs/faster_rcnn/dawn_indomain_fasterrcnn_r50fpn_seed456/evaluation/rain/coco_instances_results.json
[07/16 09:55:24 d2.evaluation.coco_evaluation]: Evaluating predictions with unofficial COCO API...
Loading and preparing results...
DONE (t=0.00s)
creating index...
index created!
[07/16 09:55:24 d2.evaluation.fast_eval_api]: Evaluate annotation type *bbox*
[07/16 09:55:24 d2.evaluation.fast_eval_api]: COCOeval_opt.evaluate() finished in 0.01 seconds.
[07/16 09:55:24 d2.evaluation.fast_eval_api]: Accumulating evaluation results...
[07/16 09:55:24 d2.evaluation.fast_eval_api]: COCOeval_opt.accumulate() finished in 0.01 seconds.
 Average Precision  (AP) @[ IoU=0.50:0.95 | area=   all | maxDets=100 ] = 0.390
 Average Precision  (AP) @[ IoU=0.50      | area=   all | maxDets=100 ] = 0.620
 Average Precision  (AP) @[ IoU=0.75      | area=   all | maxDets=100 ] = 0.471
 Average Precision  (AP) @[ IoU=0.50:0.95 | area= small | maxDets=100 ] = 0.187
 Average Precision  (AP) @[ IoU=0.50:0.95 | area=medium | maxDets=100 ] = 0.385
 Average Precision  (AP) @[ IoU=0.50:0.95 | area= large | maxDets=100 ] = 0.387
 Average Recall     (AR) @[ IoU=0.50:0.95 | area=   all | maxDets=  1 ] = 0.187
 Average Recall     (AR) @[ IoU=0.50:0.95 | area=   all | maxDets= 10 ] = 0.459
 Average Recall     (AR) @[ IoU=0.50:0.95 | area=   all | maxDets=100 ] = 0.471
 Average Recall     (AR) @[ IoU=0.50:0.95 | area= small | maxDets=100 ] = 0.250
 Average Recall     (AR) @[ IoU=0.50:0.95 | area=medium | maxDets=100 ] = 0.414
 Average Recall     (AR) @[ IoU=0.50:0.95 | area= large | maxDets=100 ] = 0.426
[07/16 09:55:24 d2.evaluation.coco_evaluation]: Evaluation results for bbox:
|   AP   |  AP50  |  AP75  |  APs   |  APm   |  APl   |
|:------:|:------:|:------:|:------:|:------:|:------:|
| 39.025 | 62.044 | 47.136 | 18.688 | 38.482 | 38.699 |
[07/16 09:55:24 d2.evaluation.coco_evaluation]: Per-category bbox AP:
| category   | AP     | category   | AP     | category   | AP     |
|:-----------|:-------|:-----------|:-------|:-----------|:-------|
| person     | 25.943 | bicycle    | nan    | car        | 52.345 |
| motorcycle | nan    | bus        | 35.347 | truck      | 42.466 |

Evaluating DAWN SNOW...
WARNING [07/16 09:55:24 d2.evaluation.coco_evaluation]: COCO Evaluator instantiated using config, this is deprecated behavior. Please pass in explicit arguments instead.
[07/16 09:55:24 d2.evaluation.coco_evaluation]: Trying to convert 'dawn_test_snow' to COCO format ...
WARNING [07/16 09:55:24 d2.data.datasets.coco]: Using previously cached COCO format annotations at '/content/drive/MyDrive/Dissertation/Runs/faster_rcnn/dawn_indomain_fasterrcnn_r50fpn_seed456/evaluation/snow/dawn_test_snow_coco_format.json'. You need to clear the cache file if your dataset has been modified.
[07/16 09:55:25 d2.data.build]: Distribution of instances among all 6 categories:
|  category  | #instances   |  category  | #instances   |  category  | #instances   |
|:----------:|:-------------|:----------:|:-------------|:----------:|:-------------|
|   person   | 13           |  bicycle   | 0            |    car     | 224          |
| motorcycle | 0            |    bus     | 2            |   truck    | 19           |
|            |              |            |              |            |              |
|   total    | 258          |            |              |            |              |
[07/16 09:55:25 d2.data.dataset_mapper]: [DatasetMapper] Augmentations used in inference: [ResizeShortestEdge(short_edge_length=(800, 800), max_size=1333, sample_style='choice')]
[07/16 09:55:25 d2.data.common]: Serializing the dataset using: <class 'detectron2.data.common._TorchSerializedList'>
[07/16 09:55:25 d2.data.common]: Serializing 40 elements to byte tensors and concatenating them all ...
[07/16 09:55:25 d2.data.common]: Serialized dataset takes 0.03 MiB
[07/16 09:55:25 d2.evaluation.evaluator]: Start inference on 40 batches
[07/16 09:55:33 d2.evaluation.evaluator]: Inference done 11/40. Dataloading: 0.5287 s/iter. Inference: 0.0304 s/iter. Eval: 0.0003 s/iter. Total: 0.5594 s/iter. ETA=0:00:16
[07/16 09:55:38 d2.evaluation.evaluator]: Inference done 21/40. Dataloading: 0.5127 s/iter. Inference: 0.0330 s/iter. Eval: 0.0003 s/iter. Total: 0.5460 s/iter. ETA=0:00:10
[07/16 09:55:43 d2.evaluation.evaluator]: Inference done 35/40. Dataloading: 0.4290 s/iter. Inference: 0.0316 s/iter. Eval: 0.0003 s/iter. Total: 0.4610 s/iter. ETA=0:00:02
[07/16 09:55:45 d2.evaluation.evaluator]: Total inference time: 0:00:15.605327 (0.445866 s / iter per device, on 1 devices)
[07/16 09:55:45 d2.evaluation.evaluator]: Total inference pure compute time: 0:00:01 (0.031322 s / iter per device, on 1 devices)
[07/16 09:55:46 d2.evaluation.coco_evaluation]: Preparing results for COCO format ...
[07/16 09:55:46 d2.evaluation.coco_evaluation]: Saving results to /content/drive/MyDrive/Dissertation/Runs/faster_rcnn/dawn_indomain_fasterrcnn_r50fpn_seed456/evaluation/snow/coco_instances_results.json
[07/16 09:55:46 d2.evaluation.coco_evaluation]: Evaluating predictions with unofficial COCO API...
Loading and preparing results...
DONE (t=0.00s)
creating index...
index created!
[07/16 09:55:46 d2.evaluation.fast_eval_api]: Evaluate annotation type *bbox*
[07/16 09:55:46 d2.evaluation.fast_eval_api]: COCOeval_opt.evaluate() finished in 0.01 seconds.
[07/16 09:55:46 d2.evaluation.fast_eval_api]: Accumulating evaluation results...
[07/16 09:55:46 d2.evaluation.fast_eval_api]: COCOeval_opt.accumulate() finished in 0.01 seconds.
 Average Precision  (AP) @[ IoU=0.50:0.95 | area=   all | maxDets=100 ] = 0.497
 Average Precision  (AP) @[ IoU=0.50      | area=   all | maxDets=100 ] = 0.749
 Average Precision  (AP) @[ IoU=0.75      | area=   all | maxDets=100 ] = 0.554
 Average Precision  (AP) @[ IoU=0.50:0.95 | area= small | maxDets=100 ] = 0.063
 Average Precision  (AP) @[ IoU=0.50:0.95 | area=medium | maxDets=100 ] = 0.440
 Average Precision  (AP) @[ IoU=0.50:0.95 | area= large | maxDets=100 ] = 0.536
 Average Recall     (AR) @[ IoU=0.50:0.95 | area=   all | maxDets=  1 ] = 0.262
 Average Recall     (AR) @[ IoU=0.50:0.95 | area=   all | maxDets= 10 ] = 0.527
 Average Recall     (AR) @[ IoU=0.50:0.95 | area=   all | maxDets=100 ] = 0.543
 Average Recall     (AR) @[ IoU=0.50:0.95 | area= small | maxDets=100 ] = 0.082
 Average Recall     (AR) @[ IoU=0.50:0.95 | area=medium | maxDets=100 ] = 0.508
 Average Recall     (AR) @[ IoU=0.50:0.95 | area= large | maxDets=100 ] = 0.575
[07/16 09:55:46 d2.evaluation.coco_evaluation]: Evaluation results for bbox:
|   AP   |  AP50  |  AP75  |  APs  |  APm   |  APl   |
|:------:|:------:|:------:|:-----:|:------:|:------:|
| 49.716 | 74.945 | 55.415 | 6.311 | 43.974 | 53.617 |
[07/16 09:55:46 d2.evaluation.coco_evaluation]: Per-category bbox AP:
| category   | AP     | category   | AP     | category   | AP     |
|:-----------|:-------|:-----------|:-------|:-----------|:-------|
| person     | 58.868 | bicycle    | nan    | car        | 54.465 |
| motorcycle | nan    | bus        | 72.525 | truck      | 13.005 |

,dataset,model,experiment,seed,condition,mAP50-95,mAP50,mAP75
0,DAWN,Faster R-CNN,in_domain,456,global,0.422588,0.664261,0.461324
1,DAWN,Faster R-CNN,in_domain,456,fog,0.380351,0.622891,0.358460
2,DAWN,Faster R-CNN,in_domain,456,rain,0.390254,0.620438,0.471364
3,DAWN,Faster R-CNN,in_domain,456,snow,0.497159,0.749454,0.554149

### **FPS**

In [20]:
def get_image_paths_from_split(voc_root, split_name):
    split_file = voc_root / "ImageSets" / "Main" / f"{split_name}.txt"

    with open(split_file, "r") as f:
        image_ids = [line.strip() for line in f if line.strip()]

    return [
        voc_root / "JPEGImages" / f"{image_id}.jpg"
        for image_id in image_ids
        if (voc_root / "JPEGImages" / f"{image_id}.jpg").exists()
    ]


def measure_fps(predictor, image_paths, warmup=20):
    images = []

    for p in image_paths:
        img = cv2.imread(str(p))
        if img is not None:
            images.append(img)

    for img in images[:warmup]:
        _ = predictor(img)

    if torch.cuda.is_available():
        torch.cuda.synchronize()

    times = []

    for img in images:
        start = time.perf_counter()
        _ = predictor(img)

        if torch.cuda.is_available():
            torch.cuda.synchronize()

        end = time.perf_counter()
        times.append(end - start)

    avg_ms = np.mean(times) * 1000
    fps = 1000 / avg_ms

    return avg_ms, fps

In [21]:
split_mapping = {
    "fog": "test_fog",
    "rain": "test_rain",
    "snow": "test_snow",
}

fps_data = {}

for condition, split_name in split_mapping.items():
    image_paths = get_image_paths_from_split(DAWN_VOC_ROOT, split_name)

    inference_ms, fps = measure_fps(
        predictor,
        image_paths,
        warmup=20
    )

    fps_data[condition] = {
        "Inference_ms_per_image": inference_ms,
        "FPS": fps
    }

    print(condition, inference_ms, fps)

fog 49.55869786666275 20.178092707166993
rain 49.95005257500793 20.019998947915848
snow 49.21201652499576 20.320240270830602

In [22]:
for idx, row in results_df.iterrows():
    condition = row["condition"]

    if condition == "global":
        results_df.loc[idx, "Inference_ms_per_image"] = np.mean(
            [v["Inference_ms_per_image"] for v in fps_data.values()]
        )
        results_df.loc[idx, "FPS"] = np.mean(
            [v["FPS"] for v in fps_data.values()]
        )
    else:
        results_df.loc[idx, "Inference_ms_per_image"] = fps_data[condition]["Inference_ms_per_image"]
        results_df.loc[idx, "FPS"] = fps_data[condition]["FPS"]

results_df

,dataset,model,experiment,seed,condition,mAP50-95,mAP50,mAP75,Inference_ms_per_image,FPS
0,DAWN,Faster R-CNN,in_domain,456,global,0.422588,0.664261,0.461324,49.573589,20.172777
1,DAWN,Faster R-CNN,in_domain,456,fog,0.380351,0.622891,0.358460,49.558698,20.178093
2,DAWN,Faster R-CNN,in_domain,456,rain,0.390254,0.620438,0.471364,49.950053,20.019999
3,DAWN,Faster R-CNN,in_domain,456,snow,0.497159,0.749454,0.554149,49.212017,20.320240

### **Sav**

# **Save training loss**

In [24]:
results_csv = OUTPUT_DIR / "dawn_faster_rcnn_in_domain_seed456_results_summary.csv"
results_json = OUTPUT_DIR / "dawn_faster_rcnn_in_domain_seed456_results_summary.json"

results_df.to_csv(results_csv, index=False)

with open(results_json, "w") as f:
    json.dump(
        results_df.to_dict(orient="records"),
        f,
        indent=4
    )

print("Saved:")
print(results_csv)
print(results_json)

Saved:
/content/drive/MyDrive/Dissertation/Runs/faster_rcnn/dawn_indomain_fasterrcnn_r50fpn_seed456/dawn_faster_rcnn_in_domain_seed456_results_summary.csv
/content/drive/MyDrive/Dissertation/Runs/faster_rcnn/dawn_indomain_fasterrcnn_r50fpn_seed456/dawn_faster_rcnn_in_domain_seed456_results_summary.json